### PR TITLE
VCS_VERSION: remove Subversion support, add support for Git & tarball

### PR DESCRIPTION
**Pull request by a-detiste**
`ShellInABox version 2.15 (revision 89e40c5)`

building from tarball can be tested this way:

```
rsync -avix . /tmp/shellinabox --exclude-from=.gitignore --exclude=.git --delete --delete-excluded
(cd /tmp/shellinabox && autoreconf -i && ./configure && make && ./shellinaboxd --version)
```

### CODE REVIEW

**Comment by KLuka** [comment]
Thanks, this is ok...

We just need to fix VERSION macro expansing in the file `shellinabox/shell_in_a_box.jspp` in method `ShellInABox.prototype.about`. 

It expands to `"2.15 (revision @VCS_REVISION@)"`, but I don't know why. Could you please check this...

**Comment by a-detiste** [comment]
Indeed, I forgotten the 'about' dialog box.

**Comment by KLuka** [comment]
I think that [Makefile.am on line 324](https://github.com/shellinabox/shellinabox/blob/master/Makefile.am#L324) is the cause for this...

**Comment by a-detiste** [comment]
I'm reviewing clean-local: too, to also delete the .js generated files

**Comment by KLuka** [comment]
Ok, you can add the fixes to this PR...

**Comment by KLuka** [comment]
Thanks, now it works and looks OK :smile:

**Pull request merged**
