### PR TITLE
typos

### PR DESCRIPTION
**Pull request by a-detiste**
the one in help snippt shellinaboxd.c is particularly bothersome; the option processing is already right

### CODE REVIEW

**Comment by KLuka** [comment]
Thanks @a-detiste :+1: Nice to hear from you :)

**Comment by a-detiste** [comment]
I'm doing fine, have a new job since 1st of March. Had to write .bat files; that hurt my brains so much after 20 years.

**Comment by KLuka** [comment]
Haha, I can only imagine your pain :) Anyway, congrats ;)

**Comment by a-detiste** [comment]
My crappy ISP put me behind a Carrier Grade Nat without notice nor consent... Baaad fo SIAB usage.

**Pull request merged**
