### PR TITLE
#342 Adding selinux policy. TODO: Unconfined context misuse needed to fix

### LINKED ISSUE #342: LOGIN service not working on CentOS 7 (SELinux)
On CentOS 7 shellinabox cannot properly execute `/bin/login` and we get `login -- <user>: no shell: Permission denied` error message displayed in browser... 

This is probably related to SELinux policy. Here is the diff of SELinux config for `shellinaboxd` process:

* CentOS 6: `system_u:system_r:initrc_t:s0`
* CentOS 7: `system_u:system_r:unconfined_service_t:s0`

Additional info in #334, #327...

### PR DESCRIPTION
**Pull request by claneys**
#342 : module for shellinaboxd daemon.

There is still a problem using unconfined context transition when launching /bin/login but it's functional.

You need to execute the shellinaboxd.sh script as root to install the policy in your system. It also generate a RPM files that can be deployed on others systems.

### CODE REVIEW

**Comment by KLuka** [comment]
Hello, thanks for the PR. I tested it and after installing built rpm shellinabox started working as expected.

I have just couple suggestions :) Please move files to `misc/selinux` directory and add README file with instructions that cover below cases...

At first I got this error, which can be resolved with `yum install selinux-policy-devel rpm-build`.

```
[centos@lkra-centos-7 shellinabox]$ sudo ./shellinaboxd.sh
Building and Loading Policy
+ make -f /usr/share/selinux/devel/Makefile shellinaboxd.pp
make: /usr/share/selinux/devel/Makefile: No such file or directory
make: *** No rule to make target `/usr/share/selinux/devel/Makefile'.  Stop.
+ exit
```

After rpm was built I needed to install it and restart shellinabox service. Like this:
```
rpm -ivh shellinaboxd_selinux-1.0-1.el7.centos.src.rpm
service shellinaboxd restart
```

**Comment by claneys** [comment]
Ok, I'll make that.

You want binary pp module file directly provided in source ? I'm not so familiar with selinux module packaging/providing but i'll make some search.

**Comment by KLuka** [comment]
Thanks :+1: 

I meant to say that there is no need to commit .pp and some others files, since they are automatically generated by your script (see edit 3 in my previous post).

**Comment by claneys** [comment]
Ok I think, it's good. Can you test it please ?

**Comment by claneys** [comment]
Any news ?

**Comment by KLuka** [comment]
Hi, sorry for the late response. I will merge this in soon, and if you have any more improvements you can add them.

Can I just ask you to squash your commits into one. Thanks.

**Comment by claneys** [comment]
Done

**Comment by KLuka** [comment]
Thank you 👍

**Pull request merged**
