### PR TITLE
Implement a change log

### PR DESCRIPTION
**Pull request by Grimthorr**
Replaced old change log file with a GitHub-friendly version which loosely follows the http://keepachangelog.com convention. Added missing updates from original author, the changes made in 2012 and our current progress this year.

Do you think we should start logging the changes we make in this repository? Is it also worth bumping the version numbers & creating releases?

### CODE REVIEW

**Comment by KLuka** [comment]
That is great, we should do that so that new users can see what has been fixed :+1:

For tagging the release 2.15 we should wait for couple more fixes and than we can build .deb package. I already raised version to 2.15 with commit 61184ca8a5bfbbedc07f89dbbec2e2ef25a0f76a.

**Comment by Grimthorr** [comment]
Ok brilliant :+1:.

I've just noticed that the Makefiles reference the old change log file name. Would deleting the old one make the build fail? If needed, commit 52acf0a6f2c90a252f05b005d96dcf4302b6b91f should point them to the new file.

**Comment by KLuka** [comment]
Yes it does, please issue another pull request :)

```
lkra@lkra-vm:~/Projects/shellinabox$ autoreconf -i
libtoolize: Consider adding `-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
Makefile.am: required file `./ChangeLog' not found
autoreconf: automake failed with exit status: 1
```

**Comment by Grimthorr** [comment]
Oops my bad, rushing my commits! See #294.

**Pull request merged**
