### PR TITLE
fix building with debuild 

### PR DESCRIPTION
**Pull request by a-detiste**

### CODE REVIEW

**Comment by a-detiste** [comment]
* add build-dep on `dh_autoreconf`
* remove more autogenerated cruft

**Comment by KLuka** [comment]
With `dpkg-buildpackage -b` I got the error bellow. After I installed dh-autoreconf, the build was successful. 

Can you please add `dh-autoreconf` to README.md file, under "Build > Install dependencies" section.

```
dpkg-buildpackage: source package shellinabox
dpkg-buildpackage: source version 2.15-1
dpkg-buildpackage: source distribution UNRELEASED
dpkg-buildpackage: source changed by Alexandre Detiste <alexandre.detiste@gmail.com>
dpkg-buildpackage: host architecture i386
 dpkg-source --before-build shellinabox_debuild
dpkg-checkbuilddeps: Unmet build dependencies: dh-autoreconf
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
```

**Comment by a-detiste** [comment]
Ok will do.

What's the purpose of INSTALL.Debian that hasn't been touched since 2009 ?  
Mislead people ? :grimacing:

Is there anything there worth moving into README.md ? The rest could be nuked ?

**Comment by a-detiste** [comment]
In fact you only need to ask to run `apt-get install git libssl-dev libpam0g-dev zlib1g-dev dh-autoreconf` this will pull all the other .deb automaticaly (ssl-dev pulls ssl, pam-dev pulls pam, dh-autorefonf pulls most of the rest)

**Comment by KLuka** [comment]
That is even better :+1: For the INSTALL.Debian file you can decide what to do. Maybe it is the best to remove the file and move some useful stuff about configuration and service start to README.md.

**Comment by a-detiste** [comment]
Ok, I'll first have a look at changes needed at horrible https://github.com/shellinabox/shellinabox/blob/master/debian/shellinabox.init full of sed magic before documenting it.

**Comment by KLuka** [comment]
Ok, thanks. Will you countinue to work on this pull request or should I merge this in and you will open another?

**Comment by a-detiste** [comment]
You can close this one, this was juste the "low hanging fruit".  

Having a look at the init script; make it work with systemd, reviewing debian/rules , INSTALL.Debian will take more time and deserve a P.R. on it's own.

**Pull request merged**
