### PR TITLE
Issue #243: Cannot look up group "shellinabox" at service start

### PR DESCRIPTION
**Pull request by tickelton**
_SC_GETGR_R_SIZE_MAX was treated as a maximum buffer size while
it should only be a proposition for an initial size.

The buffer size is now increased dynamically if the initial size
is not sufficient.

### CODE REVIEW

**Comment by tickelton** [comment]
The Issue here is that the size of the buffer used in getgrnam_r is determined by querying _SC_GETGR_R_SIZE_MAX.
If that buffer turns out to be to small getgrnam_r will fail.
Older versions of the manpage of getgrnam_r desribed _SC_GETGR_R_SIZE_MAX as the maximum size of a buffer the function can handle, while actually (and also in newer versions of the man page) that size is only a recommendation but can be increased if it is not sufficient.

**Comment by KLuka** [comment]
@tickelton Thanks :+1:

**Comment by nicocesar** [comment]
Seems that shellinabox 2.14 has this issue. But I don't know How can I correlate github development with releases ?

**Comment by KLuka** [comment]
Hi @nicocesar, shellinabox 2.14 was not released from here :) It was released 3 years ago from original Google Code repo and it was the latest version until 3 days ago when we released 2.15 and 2.16 :)

If you have this problem, use our versions of shellinabox and it should be OK... You can build your own package or download them from [here](https://packages.debian.org/unstable/shellinabox), if you are using Debian based system.

**Pull request merged**
