### PR TITLE
Kill children with HUP instead of TERM at end of session

### PR DESCRIPTION
**Pull request by BenjiWiebe**

### CODE REVIEW

**Comment by KLuka** [comment]
I gave this a quick test on Ubuntu and it seems that it is not working correctly. Child processes just ignore SIGHUP. Is it working for you?

```
[server] Command line:  ./shellinaboxd --debug -t -u luka -g luka -p 5001 -s /:luka:luka:/tmp:/tmp/sleep.sh
...
[server] Timeout. Closing session!
[server] Session Vup33OVWUt62jGYUaDvnWg done.
[server] Terminating child 19885! [kill]
[server] Timeout. Closing session!
[server] Session rMZi24C-vwzoWNpjLC/lWQ done.
[server] Terminating child 19893! [kill]
[server] Timeout. Closing session!
[server] Session 7wHhEjTi9Y74kYA9R6wZoQ done.
[server] Terminating child 19903! [kill]
[server] Timeout. Closing session!
[server] Session yYRyMWdNJRRs4JFvLifirQ done.
[server] Terminating child 19917! [kill]
```

**Comment by BenjiWiebe** [comment]
Huh. Didn't test it, since this is the same behavior that bash uses to kill backgrounded processes when you exit (unless, of course, you have disabled that).

**Comment by KLuka** [comment]
Yep I guess that it is disabled in launcher.c:

```c
  // pututxline() can cause spurious SIGHUP signals. Better ignore those.
  signal(SIGHUP, SIG_IGN);
```

Since I am not the author of this code I don't know how safe would be to re enable this signal...

**Comment by BenjiWiebe** [comment]
No, that is shellinaboxd that is ignoring SIGHUP. That should not affect children. (If it does, that's really wierd.)  [Here](http://unix.stackexchange.com/a/15603) is a brief explanation of what SIGHUP is for.

**Comment by BenjiWiebe** [comment]
Actually, it appears that the children *do* inherit signal masks by default.

**Comment by KLuka** [comment]
Yep. After I removed the `signal(SIGHUP, SIG_IGN);` it started to work ok with SIGHUP signal. I am still not sure what is the correct thing to do here...

**Comment by BenjiWiebe** [comment]
It would seem that there should be a way to give children the default sigactions. That's what should be done, I think.
Maybe just resetting the sigaction in the child after fork and before exec?

**Comment by BenjiWiebe** [comment]
Wierd, I'm seeing that the line you commented out *does* run in the child. Now, why would pututxline() in the parent cause HUP's to be sent to the *children*?

**Comment by BenjiWiebe** [comment]
I added another commit. This one resets the handler in the child to the default. The children now properly handle HUP. Log file excerpt:

    [server] Timeout. Closing session!
    [server] Session m79etw9x86uvEpoc/JVeTg done.
    [server] Terminating child 32647! [HUP]
    [server] Child 32647 exited with exit code 0.
    [server] Timeout. Closing session!
    [server] Session Awli1udv7l1Oq1KJeWGK/g done.
    [server] Terminating child 32660! [HUP]
    [server] Child 32660 exited with exit code 0.
    [server] Timeout. Closing session!
    [server] Session LrT3RhDeSA7gsp9p9f4TzA done.
    [server] Terminating child 32669! [HUP]
    [server] Child 32669 exited with exit code 0.
    [server] Timeout. Closing session!
    [server] Session NXmC2Tm5NQYtqIqVUlDxmQ done.
    [server] Terminating child 32681! [HUP]
    [server] Child 32681 exited with exit code 0.
    [server] Timeout. Closing session!
    [server] Session 4h8OTG48UcfSTlc7P0hwlg done.
    [server] Terminating child 32697! [HUP]
    [server] Timeout. Closing session!
    [server] Session zNgEviEOJGcPKrJ-lIgRTw done.
    [server] Terminating child 32715! [HUP]
    [server] Child 32715 exited with exit code 0.
    [server] Child 32697 exited with exit code 0.

**Comment by BenjiWiebe** [comment]
Also, about the correct thing to do. I think this is the correct thing to do. That line you brought to my attention is setting the launcher's thread to ignore HUPs generated by pututxline. Now, the launcher *still* ignores the HUPs, but when it starts a child the child then starts paying attention to HUPs.

**Comment by KLuka** [comment]
Great solution :+1: I tested it also with SSH and LOGIN service. Thanks you for your patches.

I also noticed that when using LOGIN service with sudo command `kill()` function returns an error (as it should) but the child exits anyway. Do you have any clue what is happening here? This may actually be the complete solution for #103 :smile: 

```
[server] Command line:  ./shellinaboxd -d -u shellinabox -g shellinabox -t -s /:LOGIN -p 5002
...
[server] Timeout. Closing session!
[server] Session c-dwj7RG7UaxeeXCXbR8mw done.
[server] Terminating child 25712 failed! [Operation not permitted]
[server] Child 25712 exited with exit code 0.
[server] Timeout. Closing session!
[server] Session T8hUwBayoSkWyrJYoXy/NA done.
[server] Terminating child 25713 failed! [Operation not permitted]
```

LOGIN processes, before they were killed:
```
4     0 25712 25709  20   0   4600  3636 wait   Ss   pts/15     0:00 login -p -h luka-pc
4     0 25713 25709  20   0   4600  3644 wait   Ss   pts/16     0:00 login -p -h luka-pc
```

**Comment by BenjiWiebe** [comment]
I can maybe test it, once I figure out what you mean. :smiley:

**Comment by KLuka** [comment]
Haha, yes I need some sleep :smiley: Can you try this command and see what happens with child processes when you close browsers window:

```
sudo ./shellinaboxd -d -u shellinabox -g shellinabox -t -s /:LOGIN -p 5001
```

**Comment by BenjiWiebe** [comment]
*Posting results in #103 instead of here, since you said it was unrelated to my patch.*

**Pull request merged**
