### PR TITLE
Message passing to embedded shellinabox

### PR DESCRIPTION
**Pull request by KLuka**
Added support for messages passing to or from embedded shellinabox frame. This has to be enabled with --messages-origin command line switch. Example file with additional info and instructions on how to use this feature was also added.

### CODE REVIEW

**Comment by KLuka** [comment]
Any comments? :smile:

**Comment by a-detiste** [comment]
That seems sooo abstract to mee, can you add a more down to earth example ?

Like a bare HTML calculator keypad where operations got translated in `echo 2 + 2 | bc` or such.

Only implementing addition operator would already be enough to see how it works.

Maybe an online demo ? (but that needs hosting) a screenshot would already be nice.

**Comment by KLuka** [comment]
Perhaps you are right :smile: This really is a complicated example, but it kinda shows whole functionality. I will add something more simple in example comments. Maybe something like this, which shows us how to pass just one command to shellianbox:

```javascript
shellinaboxIFrame.contentWindow.postMessage(JSON.stringify(
	type : "input",
	data : "ls -l\n"
), shellinaboxUrl);
```
I also noticed an error in example file. Origin in example for `shellinaboxd -p 4200 -m 'https://192.168.1.150:4200'` should be passed with port of a parent window. Like this for example `shellinaboxd -p 4200 -m 'https://192.168.1.150'`.

Oh and here is a screen shot of working example:

shellinabox

**Comment by KLuka** [comment]
@a-detiste I added additional info. Does the example file make more sense now?

**Comment by a-detiste** [comment]
Thats nice :-) remind be of some VisualBasic applications that embed a 3270 ;-)

**Comment by KLuka** [comment]
This is merged in, if anyone has more questions, suggestions or comments please post them here...

Issue #253 will be closed, since we have working example on how to embed shellinabox. And I think that issue #157 could be solved with this new feature, but I am not so sure...

**Comment by nishantkr0208** [comment]
I have embedded  shellinabox in my application using iframe. it working fine now i am trying to pass message to iframe but nothing happening. there is a step in embedded.html 
>shellinaboxd -p myPort -m 'https://myIp' 

when i am trying to run it on terminal after enter it does not start server and goes into infinite wait.
screenshot

**Comment by KLuka** [comment]
Try to run shellinabox with this command: `shellinaboxd --debug -p myPort -m '*' `

**Comment by nishantkr0208** [comment]
it's running in debug mode but how to run in daemon mode in background.

**Comment by nishantkr0208** [comment]
btw thank you so much for reply..

**Comment by Chisha14** [comment]
@KLuka  The embedded.html file didn't work for me on Chrome nor IExplorer! Any help?
Note: Didn't test it on FireFox.
Thanks in advance :)

**Comment by JohannesTK** [comment]
Great functionality!

Do you have any ideas how to forward a CTL+C (SIGTERM)?

**Pull request merged**
