### PR TITLE
Fix build error caused by #293

### PR DESCRIPTION
**Pull request by Grimthorr**
Sorry :smile:.

### CODE REVIEW

**Comment by KLuka** [comment]
No problem :smile:

**Comment by KLuka** [comment]
Hmm ... command `autoreconf -i` still doesn't work. I think that we need ChangeLog file even if it is empty.

More info: https://www.sourceware.org/autobook/autobook/autobook_28.html

**Comment by Grimthorr** [comment]
Damn that's annoying! Hmm, we could rename the file back to ChangeLog or just add an empty one then?

**Comment by KLuka** [comment]
It could be empty with some warning like: "Dummy ChangeLog" or something :)

**Comment by Grimthorr** [comment]
Sure or just "see CHANGELOG.md" :+1:. What a nightmare!

**Comment by KLuka** [comment]
Hehe ... done :+1:

**Pull request merged**
